

version: 0.2

phases:
  install:
    runtime-versions:
        golang: 1.12
    commands:
      - echo Entered the install phase...
      # - apt-get install hugo . # was installing an old version. I need 0.59+
      - apt-get -qq update && apt-get -qq install curl
      - apt-get -qq install asciidoctor
      - curl -s -L https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb -o hugo.deb
      - dpkg -i hugo.deb
      - hugo env
    finally:
      - echo Installation done

  build:
    commands:
      - echo Entered the build phase ...
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - hugo --environment aws
    finally:
      - echo Building the HTML files finished
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/public/
  discard-paths: no

