

version: 0.2

phases:
  install:
    runtime-versions:
        golang: 1.12
    commands:
      - echo Entered the install phase...
      - wget https://github.com/gohugoio/hugo/releases/download/v0.129.0/hugo_extended_0.129.0_linux-amd64.deb -O /tmp/hugo.deb
      - apt-get install -y ./tmp/hugo.deb
      - hugo env
    finally:
      - echo Installation done

  build:
    commands:
      - echo Entered the build phase ...
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - hugo --environment aws
    finally:
      - echo Building the HTML files finished
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/public/
  discard-paths: no

