name: DeployToAzure

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install
      uses: peaceiris/actions-hugo@v2

    - name: Build
      run: |
        hugo version
        env HUGO_ENV="production" hugo --environment azure
        
    - name: Deploy
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob sync -c '$web' -s "public" --account-name ${{ secrets.AZURE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_ACCOUNT_KEY }}
          
          
          
          
