name: DeployToGCP

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Install
      uses: peaceiris/actions-hugo@v2
       
    - name: Build
      run: |
        hugo version
        env HUGO_ENV="production" hugo --environment gcp
        
    - name: Login
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GOOGLE_SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        
    - name: Deploy
      run: |
        gsutil -m rsync -R public gs://blog.brianbeach.com
