name: DeployToGCP

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.59.1'
        # extended: true

    - name: Build
      run: env HUGO_ENV="production" hugo --environment gcp
        
    - name: Login
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        
    - name: Deploy
      uses: docker://gcr.io/cloud-builders/gsutil
      with:
        args: rsync -R public gs://blog.brianbeach.coim
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          
